### PR TITLE
Update homework_2.sql

### PR DESCRIPTION
**Pull request by lllllwang1**
## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
I tried to pull the request correctly.
## What did you learn from the changes you have made?
I followed the guidence of submitting assignment.
## Checklist
- [x ] I can confirm that my changes are working as intended

### CODE REVIEW

**Comment by SidraBushra** [comment]
I still cannot see the code for your HW2. I can see your commit, but nothing inside.

**Comment by lllllwang1** [comment]
I update the homework_2.sql file in main branch and create a new branch before I pull the request. But I have tried again and there is nothing change show. Could you help me to walk through that?

Thanks in advance.
Shaohe Wang

**Comment by SidraBushra** [comment]
I think, try to upload file again on the branch.

**Comment by lllllwang1** [comment]
[homework_2.sql.zip](https://github.com/lllllwang1/sql/files/15396437/homework_2.sql.zip)
Hi, I just uploaded homework_2.zip. Please check if this one is working. Thanks.

**Comment by lllllwang1** [comment]
Hi,

I just uploaded the file as .zip to the pull request. Please check if this one works.

Thanks,
Shaohe Wang

**Pull request merged**
